//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderHeaderId { get; set; }
        public int ShawarmaId { get; set; }
        public int Quantity { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
        public virtual Shawarma Shawarma { get; set; }
    }
}
