//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        public int OrderHeaderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int SellerId { get; set; }
    
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
