//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceController
    {
        public int PriceControllerId { get; set; }
        public int ShawarmaId { get; set; }
        public decimal Price { get; set; }
        public int SellingPointId { get; set; }
        public string Comment { get; set; }
    
        public virtual Shawarma Shawarma { get; set; }
        public virtual SellingPoint SellingPoint { get; set; }
    }
}
